### ISSUE TITLE
Broken/Missing Links to Tutorials

### ISSUE THREAD

**Issue by gpjr** [SECapstone/capstone#3]
The links to the Resources at the bottom of Sprint0.md seem to be broken (404 Page Not Found Error).

https://github.com/SECapstone/capstone/blob/resources/git.md
https://github.com/SECapstone/capstone/blob/resources/typescript.md
https://github.com/SECapstone/capstone/blob/resources/async.md
https://github.com/SECapstone/capstone/blob/resources/promises.md

Links 3 & 4 (Async Development Tutorial & Promises Tutorial) seem like they'd be particularly useful to have. Can these links be fixed or can an alternative source for these tutorials be provided?

**Comment by braxtonhall** [comment]
Finally addressed in [PR#6](https://github.com/SECapstone/capstone/pull/6)
